<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <TargetFramework>net10.0</TargetFramework>
        <Version>1.1.4</Version>
        <Authors>Aleksander Laasmägi</Authors>
        <Company>alaasmagi</Company>
        <PackageId>alaasmagi.Base.Message.RabbitMQ</PackageId>
        <Description>Base Message RabbitMQ package for .NET webapps</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Base.Message.RabbitMQ</RootNamespace>
        <PackageReadmeFile>Base.NuGet.README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Base.Contracts.Message\Base.Contracts.Message.csproj" />
    </ItemGroup>

</Project>
